spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: XXX.apps.googleusercontent.com
          client-secret: XXX
          introspection-uri: "https://accounts.google.com/o/oauth2/v2/auth"